Reciepe:-
1. First we should fry Rava.
2. Add oil and fry Mustard seeds.
3. Chop all the onions, capsicum and tomato.
4. Put onions, capsicum and tomato.
5. After we have added all three of them we should add chilli after 10 seconds.
6. Fry deeply for 5 min.
7. Add water after it is fried.
8. After adding water we should add salt.
9. After Water starts boiling add rava.
10. Stir nicely and then add chopped coconut.